server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.92.70.12:3306/gaoqiyun_springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: gaoqiyun@123
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20  
mybatis-plus:
  global-config:
    id-type: 3
    field-strategy: 2 
    refresh-mapper: true
    db-column-underline: true
logging:
  level:
    com:
     solr:
      mapper: debug
  